### VARIABLES ###
@BASE_URL=http://localhost:3000/api
@ACCESS_TOKEN=
### VARIABLES ###

########### AUTH ########### 
### SIGN UP
POST {{BASE_URL}}/auth/signup
Content-Type: application/json

{
  "email": "paul@email.com",
  "password": "password",
  "repassword": "password",
  "role": "user"
}

### LOG IN
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "paul@email.com",
  "password": "password"
}

### GET USER
GET {{BASE_URL}}/auth/user
Authorization: Bearer {{ACCESS_TOKEN}}
# ~~~~~~~ END AUTH ~~~~~~~~~

########### ToDos ########### 
### CREATE TODO
POST {{BASE_URL}}/todos
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "todo": "test note"
}

### GET todo single
GET {{BASE_URL}}/todos/f1bcb35e9b0f4b8e8adabe808
Authorization: Bearer {{ACCESS_TOKEN}}

### GET TODOs
GET {{BASE_URL}}/todos
Authorization: Bearer {{ACCESS_TOKEN}}

### UPDATE AN ENTIRE ToDo
PATCH {{BASE_URL}}/todos/f1bcb35e9b0f4b8e8adabe808
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "status": "completed"
}

### DELETE ToDo
DELETE {{BASE_URL}}/todos/f1bcb35e9b0f4b8e8adabe808
Authorization: Bearer {{ACCESS_TOKEN}}

# ~~~~~~~ END ToDos ~~~~~~~~~

########### health ########### 
### GET todo single
GET {{BASE_URL}}/health

# ~~~~~~~ END health ~~~~~~~~~