### SIGN UP
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "paul@email.com",
  "password": "password",
  "repassword": "password",
  "role": "user"
}


### LOG IN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "paul@email.com",
  "password": "password"
}

### LOG IN
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ2YzhjM2IzMjk0NTQxNzU5ZjA2ZWEzNGQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoicGF1bEBlbWFpbC5jb20iLCJpYXQiOjE3NTIyMzMzODQsImV4cCI6MTc1MjIzNjk4NH0.T6c1xaQu65r76R8OzUApoNIoRs47uqIs7UOVWMbCbDI
